#+TITLE: Chu's Literate DOOM GNU Emacs Configuration
#+AUTHOR: chu the pup
#+DESCRIPTION: Chu's Literate Doom GNU Emacs configuration
#+PROPERTY: header-args :tangle yes :results none
#+startup: show2levels

* Preamble

Here's the deets:

** Org-mode babel tangle setup

There is a property defined on at the top of this file:

#+begin_example elisp
header-args :tangle yes
#+end_example

This tells Emacs to automatically tangle (include) all code blocks in this file when generating the code for the config file (~config.el~), unless the code block explicitly includes `:tangle no` as the above code block does (or if it is a quote or example block).

** Usage of quote and example blocks

What I am about to explain is typically done in order to debug the configuration on my end. However, the use of quote and example blocks also serves as a way of offering an on/off switch to certain blocks of "settings" (blocks beginning in "#+begin_something" and ending in "#+end_something"):

#+begin_quote
#+begin_example
...
#+end_example
#+end_quote

...or just delete it entirely if you don't want or need the feature / setting, for example, if you want to disable *[[id:a948faf0-c278-4481-bd1b-c857644a4c90][the active Discord presence support plugin for Emacs that I have turned on by default]]*.

I try to keep the ones seen here (as in, in this configuration) limited to settings saved for reference, debugging, or other posterity purposes, rather than leaving behind a bunch of crud and bug fixes that are no longer necessary.

* ~config.el~ lexical binding

#+begin_src elisp
;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-
#+end_src

* DOOM Emacs Documentation

Doom exposes five (optional) variables for controlling fonts in Doom. Here are the three important ones:

+ `doom-font'

+ `doom-variable-pitch-font'

+ `doom-big-font' -- used for `doom-big-font-mode'; use this for presentations or streaming.

They all accept either a font-spec, font string ("Input Mono-12"), or xlfd font string. You generally only need these two:

#+begin_example
(setq doom-font (font-spec :family "monospace" :size 12 :weight 'semi-light)
#+end_example

#+begin_example
(setq doom-variable-pitch-font (font-spec :family "sans" :size 13))
#+end_example

If you're having issues regarding fonts, you may want to [[id:24408296-5370-4dbf-a52f-f1afe865ceb5][stop Emacs from loading your Xresources file.]]

There are two ways to load a theme. Both assume the theme is installed and available. You can either set `doom-theme' or manually load a theme with the `load-theme' function. This is the default:

#+begin_example elisp
(setq doom-theme 'doom-one)
#+end_example

Here are some additional functions/macros that could help you configure Doom Emacs:

- `load!' for loading external *.el files relative to this one

- `use-package!' for configuring packages

- `after!' for running code after a package has loaded

- `add-load-path!' for adding directories to the `load-path', relative to
  this file. Emacs searches the `load-path' when you load packages with
  `require' or `use-package'.

- `map!' for binding new keys

To get information about any of these functions/macros, move the cursor over the highlighted symbol at press 'K' (non-evil users must press 'C-c c k'). This will open documentation for it, including demos of how they are used.

You can also try 'gd' (or 'C-c c d') to jump to their definition and see how they are implemented.

Place your private configuration here! Remember, you do not need to run 'doom sync' after modifying this file!

Some functionality uses this to identify you, e.g. GPG configuration, email clients, file templates and snippets.

#+begin_example elisp
(setq user-full-name "John Doe"
      user-mail-address "example@donut.arpa")
#+end_example

* Config

** Private Configuration

#+begin_src elisp
(setq user-full-name "chu the pup"
      user-mail-address "chufilthymutt@gmail.com")
#+end_src

** Visual Changes

*** Inhibit Xresources being loaded by Emacs

#+begin_src elisp
(setq inhibit-x-resources t) ; inhibit .xresources file from being loaded on emacs init
#+end_src

*** Fix alpha transparency issues

Sometimes Emacs has issues with transparency. In my case, it goes unusably transparent if I make use of an Xresources file.

You can specify frames to use different levels of transparency depending on whether or not you have Emacs focused (active) or if you've clicked off to another application (inactive).

#+begin_example elisp
(set-frame-parameter (selected-frame) 'alpha '(<active> . <inactive>))
#+end_example

Or you can just use one number, as so:

#+begin_example elisp
(set-frame-parameter (selected-frame) 'alpha <both>)
#+end_example

Here's the settings I currently use:

Set current Emacs frame's opacity to:

#+begin_src elisp
(set-frame-parameter (selected-frame) 'alpha 100)
#+end_src

Set all Emacs frames opacity from this point on to:

#+begin_src elisp
(add-to-list 'default-frame-alist '(alpha 100))
#+end_src

Set Emacs's background opacity:

#+begin_src elisp
(set-frame-parameter nil 'alpha-background 100)
#+end_src

Set all Emacs frames from this point on to have a background opacity of:

#+begin_src elisp
(add-to-list 'default-frame-alist '(alpha-background . 100))
#+end_src

from [[https://www.emacswiki.org/emacs/TransparentEmacs][EmacsWiki: Transparent Emacs]]

You may also wish to [[id:24408296-5370-4dbf-a52f-f1afe865ceb5][disable Emacs loading your Xresources file.]]

**** Font

I use the default LARBS monospace font instead of Fira Mono for consistency's sake.

#+begin_src elisp
(setq doom-font (font-spec :family "Mono" :size 12))
#+end_src

The following ensures correct font size without affecting the font used:

#+begin_example elisp
(setq doom-font (font-spec :size 12))
#+end_example

**** Temporarily convert images that Emacs cannot otherwise display

This will Set Emacs to convert images if they are going to be shown in the GUI. It detects when Emacs is unable to display the image due to lack of compatibility and temporarily converts it, pushing the converted version into memory during display (it gets cleaned up by the garbage collector).

Note: This is a soft dependency of random-splash-image; in turn, you risk being unable to display certain image file types (notably .webp files) if this is disabled.

#+begin_src elisp
(setq image-use-external-converter t)
#+end_src

**** Random Splash Images

***** Enable random-splash-image

For the plugin 'random-splash-image' which displays a random splash image on each Emacs startup.

#+begin_src elisp
(require 'random-splash-image)
#+end_src

***** Tell random-splash-image what directory to look for images in.

#+begin_src elisp
(setq random-splash-image-dir
      (concat
       (getenv "HOME")
       "/.local/share/random-splash-images/"))
#+end_src

***** IDEA Find way to set multiple directories for random-splash-image

***** Set a random splash image on Emacs startup

#+begin_src elisp
(with-eval-after-load 'random-splash-image
  (random-splash-image-set))
#+end_src

*** Alpha background transparency function :function:

Requires a compositor (xcompmgr, picom, compton (maybe (haven't tested compton))).

[[https://kristofferbalintona.me/posts/202206071000/][True Emacs Transparency | Kristoffer Balintona]]

The original by kb:

#+begin_src elisp :tangle no
(defun kb/toggle-window-transparency ()
  "Toggle transparency."
  (interactive)
  (let ((alpha-transparency 85))
    (pcase (frame-parameter nil 'alpha-background)
      (alpha-transparency (set-frame-parameter nil 'alpha-background 100))
      (t (set-frame-parameter nil 'alpha-background alpha-transparency)))))
#+end_src

My version(s):

#+begin_src elisp
(defun toggle-transparency ()
  "Toggle TOTAL EMACS X11 transparency. Might need to be called a couple of times in a row to work."
  (interactive)
  (let ((alpha (frame-parameter nil 'alpha)))
    (if (eq
     (if (numberp alpha)
         alpha
       (cdr alpha)) ; may also be nil
     100)
    (set-frame-parameter nil 'alpha '(85 . 50))
      (set-frame-parameter nil 'alpha '(100 . 100)))))
#+end_src

#+begin_src elisp
(defun toggle-background-transparency ()
  "Toggle background transparency, wherein text and other elements in frame are still displayed but a background isn't."
  (interactive)
  (if (get 'toggle-background-transparency 'state)
      (progn
        (set-frame-parameter nil 'alpha-background 100)
        (put 'toggle-background-transparency 'state nil))
    (progn
      (set-frame-parameter nil 'alpha-background 75)
      (put 'toggle-background-transparency 'state t))))
#+end_src

** A "remove all blank lines" custom script :custom:

#+begin_src elisp
(defun chu/remove-all-empty-lines ()
  (interactive)
  (save-excursion
    (goto-char (point-min))
    (flush-lines "^\\s-*$")))
#+end_src

** Org-Mode :org:

*** Org Tag List :org:

From System Crafters: [[https://www.youtube.com/watch?v=3-sLBaJAtew][Org Roam: The Best Way to Keep a Journal in Emacs - YouTube]]

#+begin_src elisp
(setq org-tag-alist
      '(;; Places
        ("@home" . ?H)
        ("@work" . ?W)

        ;; Devices
        ("@computer" . ?C)
        ("@phone" . ?P)

        ;; Activities
        ("@planning" . ?n)
        ("@programming" . ?p)
        ("@writing" . ?w)
        ("@creative" . ?c)
        ("@email" . ?e)
        ("@calls" . ?a)
        ("@errands" . ?r)))
#+end_src

*** Org TODO state hiding :org:

Write TODO state changes into LOGBOOK drawer. [[https://stackoverflow.com/a/63798475][Thanks, LeeRuns (stackoverflow.com)]].

This helps keep Org files tidier and cleaner in the case of recurring / looping tasks. You can fold them, whereas by default, the change in TODO state (e.g. from TODO -> DONE) create separate logs.

#+begin_src elisp
(setq org-log-into-drawer "LOGBOOK")
#+end_src

*** Org Babel Auto-Tangle

For the package org-babel-auto-tangle (see packages.org).

#+begin_src elisp
(add-hook 'org-mode-hook 'org-auto-tangle-mode)
#+end_src

*** Hook load fragtog

#+begin_src elisp
(add-hook 'org-mode-hook 'org-fragtog-mode)
#+end_src

*** Custom Org TODO keywords

#+begin_src elisp
(setq org-todo-keywords
       '((sequence "TODO(t)" "PROJ(p)" "LOOP(r)" "STRT(s)" "WAIT(w)" "HOLD(h)" "HABIT(H)" "IDEA(i)" "|" "DONE(d)" "KILL(k)")
         (sequence "[ ](T)" "[-](S)" "[?](W)" "|" "[X](D)")
         (sequence "|" "OKAY(o)" "YES(y)" "NO(n)")))
#+end_src

*** Ensure blank lines between headings and before contents

From alphapapa.

#+begin_src elisp
(defun ap/org-fix-blank-lines (prefix)
  "Fix blank lines (or lack thereof) between entries and between planning-lines/drawers and entry contents in current subtree.
    With prefix, operate on whole buffer."
  (interactive "P")
  (save-excursion
    (when prefix
      (goto-char (point-min)))
    (when (org-before-first-heading-p)
      (outline-next-heading))
    (ap/org-fix-blank-lines-between-subtree-nodes)
    (ap/org-fix-blank-lines-after-headings)))
#+end_src

#+begin_src elisp
(defun ap/org-fix-blank-lines-between-subtree-nodes ()
  "Make sure each heading in subtree is separated from the previous heading's content by a blank line."
  (interactive)
  (save-excursion
    (unless (org-at-heading-p)
      (org-back-to-heading))
    (ignore-errors
      ;; Try to work on the parent-level heading to fix all siblings
      ;; of current heading, but if we're at a top-level heading,
      ;; ignore the error.
      (outline-up-heading 1))
    (let ((m (point-marker)))
      (cl-flet ((fix nil (while (not (looking-back "\n\n"))
                           (insert-before-markers "\n"))))
        (org-map-entries #'fix t 'tree))
      ;; Inserting blank lines may move the point, depending on whether
      ;; it was at the beginning of a heading line or somewhere else.
      ;; Use the marker to make sure we are at the same position.
      (goto-char m)
      (org-with-wide-buffer
       ;; `org-map-entries' narrows the buffer, so `looking-back'
       ;; can't see newlines before the top heading, which may cause
       ;; extra newlines to be inserted.  Now we clean them up.
       (outline-back-to-heading)
       (while (looking-back (rx (>= 3 "\n")))
         (delete-char -1 nil)))
      (set-marker m nil))))
#+end_src

#+begin_src elisp
(defun ap/org-fix-blank-lines-after-headings ()
  "Make sure a blank line exists after a heading's drawers and planning lines, before the entry content."
  (interactive)
  (when (org-before-first-heading-p)
    (user-error "Before first heading."))
  (cl-flet ((fix nil (let ((end (org-entry-end-position)))
                       (forward-line)
                       (while (and (org-at-planning-p)
                                   (< (point) (point-max)))
                         ;; Skip planning lines
                         (forward-line))
                       (while (re-search-forward org-drawer-regexp end t)
                         ;; Skip drawers.  You might think that
                         ;; `org-at-drawer-p' would suffice, but for
                         ;; some reason it doesn't work correctly
                         ;; when operating on hidden text.  This
                         ;; works, taken from
                         ;; `org-agenda-get-some-entry-text'.
                         (re-search-forward "^[ \t]*:END:.*\n?" end t)
                         (goto-char (match-end 0)))
                       (unless (or (= (point) (point-max))
                                   (org-at-heading-p)
                                   (looking-at-p "\n"))
                         (insert "\n")))))
    (org-map-entries #'fix t 'tree)))
#+end_src

by [[https://github.com/alphapapa/unpackaged.el#ensure-blank-lines-between-headings-and-before-contents][Alphapapa]]

*** Org directories and files :org:

If you use `org' and don't want your org files in the default location below, change `org-directory'. It must be set before org loads!

**** Org root directory :org:

The following will vary, so change it to be whatever your org root directory is/what you want it to be.

I use a directory that I sync between computers with a Nextcloud server I run but you don't necessarily have to do that.

#+begin_src elisp
;; (after! 'org
  (setq org-directory
        (concat
         (getenv "HOME")
        "/Nextcloud/documents/org/"))
  ;; )
#+end_src

**** Org bookmark directory :org:

The following will vary, so change it to be whatever your bookmarks file is/what you want it to be.

I use a document that I track with org roam but you don't necessarily have to do that.

#+begin_src elisp
(with-eval-after-load 'org
  (setq +org-capture-bookmarks-file
        (concat
         (getenv "HOME")
         "/Nextcloud/documents/org/roam/20221004090130-bookmarks.org")))
#+end_src

**** Org agenda files :org:

#+begin_src elisp
(setq org-agenda-files
   '("/home/chu/Nextcloud/documents/org/roam/20220726210346-important_dates.org"
     "/home/chu/Nextcloud/documents/org/roam/20220822103211-engl_1030.org"
     "/home/chu/Nextcloud/documents/org/roam/20220823133456-precalculus_algebra.org"
     "/home/chu/Nextcloud/documents/org/roam/20220826102105-chem_1115.org"
     "/home/chu/Nextcloud/documents/org/roam/20221002161631-my_conlang.org"
     "/home/chu/Nextcloud/documents/org/roam/20221002190906-furry.org"
     "/home/chu/Nextcloud/documents/org/roam/20221004221829-todo.org"
     "/home/chu/Nextcloud/documents/org/roam/20221004221831-todo.org"
     "/home/chu/Nextcloud/documents/org/roam/20221004222234-projects.org"
     "/home/chu/Nextcloud/documents/org/roam/20221004222237-journal.org"
     "/home/chu/Nextcloud/documents/org/roam/20221004222241-notes.org"
     "/home/chu/Nextcloud/documents/org/roam/20240201170253-albums_to_download.org"
     "/home/chu/Nextcloud/documents/org/roam/20240326161621-livestreaming.org"
     "/home/chu/Nextcloud/documents/org/roam/asm/20240830094040-assembly.org"
     "/home/chu/Nextcloud/documents/org/roam/c++/20240116111203-cpp.org"
     "/home/chu/Nextcloud/documents/org/roam/daily/2024-05-08.org"
     "/home/chu/Nextcloud/documents/org/roam/engl/engl-2020/20240116095712-engl_2020.org"
     "/home/chu/Nextcloud/documents/org/roam/hist/hist-2320/20240116133242-hist_2320.org"
     "/home/chu/Nextcloud/documents/org/roam/lisp/scheme/sicp/README.org"
     "/home/chu/Nextcloud/documents/org/roam/math/20220821114043-mathematics.org"
     "/home/chu/Nextcloud/documents/org/roam/math/20240903162832-linear_algebra.org"
     "/home/chu/Nextcloud/documents/org/roam/math/20240905211621-calculus_ii.org"
     "/home/chu/Nextcloud/documents/org/roam/20220726210347-important_dates.org"))
#+end_src

Usually, you just set these using `org-agenda-file-to-front`

**** Org capture journal file location :org:

You know the gist by now--change this to whatever you want your file to be.

#+begin_src elisp
(with-eval-after-load 'org
  (setq +org-capture-journal-file
        (concat
         (getenv "HOME")
         "/Nextcloud/documents/org/roam/20221004222230-journal.org")))
#+end_src

**** Org capture journal location :org:

#+begin_src elisp
(with-eval-after-load 'org
  (setq org-journal-dir
        (concat
         (getenv "HOME")
         "/Nextcloud/documents/org/roam/journal/")))
#+end_src

**** Org notes file location :org:

#+begin_src elisp
(with-eval-after-load 'org
  (setq +org-capture-notes-file
        (concat
         (getenv "HOME")
         "/Nextcloud/documents/org/roam/20221004222235-notes.org")))
#+end_src

**** Org projects file location :org:

#+begin_src elisp
(with-eval-after-load 'org
  (setq +org-capture-projects-file
        (concat
         (getenv "HOME")
         "/Nextcloud/documents/org/roam/20221004222226-projects.org")))
#+end_src

**** Org todo file location :org:

I primarily use a "todo" file rather than an "agenda" file, for agenda ("TODO") items.

#+begin_src elisp
(with-eval-after-load 'org
  (setq +org-capture-todo-file
        (concat
         (getenv "HOME")
         "/Nextcloud/documents/org/roam/20221004221829-todo.org")))
#+end_src

**** Org Roam v2 directories and files :org:roam:

#+begin_src elisp
;; (with-eval-after-load 'org
  (setq org-roam-directory
        (concat
         (getenv "HOME")
         "/Nextcloud/documents/org/roam/"))
;; )
#+end_src

**** Org Roam v2 dailies directory :org:roam:

Path to daily-notes. This path is relative to org-roam-directory.

#+begin_src elisp
(setq org-roam-dailies-directory "daily/")
#+end_src

**** Org Roam v2 dailies capture template :org:roam:

#+begin_src elisp
(setq org-roam-dailies-capture-templates
      '(("d" "default" entry
         "* %?"
         :target (file+head "%<%Y-%m-%d>.org"
                            "#+title: %<%Y-%m-%d>\n"))))
#+end_src

**** org-roam-protocol test :org:roam:protocols:

(I don't remember why I put this here.)

#+begin_src elisp
(require 'org-roam-protocol)
#+end_src

**** org-roam-export test :org:roam:

(I don't remember why I put this here, either.)

#+begin_src elisp
(require 'org-roam-export)
#+end_src

**** Org ID: Custom ID Location :org:

#+begin_src elisp
(setq org-id-locations-file
      (concat
       (getenv "HOME")
       "/Nextcloud/documents/org/.orgids"))
#+end_src

**** Org-attach custom directory :org:

#+begin_src elisp
(setq org-attach-id-dir
      (concat
       (getenv "HOME")
       "/Nextcloud/documents/org/.attach/"))
#+end_src

**** Org-Cite (oc.el) :org:cite:

***** Bibliography Location :org:cite:bib:

#+begin_src elisp
(setq org-cite-global-bibliography
       (list
        (concat
         (getenv "HOME")
         "/Nextcloud/documents/org/roam/bib.bib")))
#+end_src

See also [[https://orgmode.org/manual/Citations.html#Citations-1][the org mode manual section on org-cite, the citation module that is native to emacs org mode]] in order to specify per-file bibliography files with .bib or .json files.

***** CiteProc Formatter File Directory Location :org:cite:citeproc:

Citation Style Language (CSL) files can be used with org-cite.

#+begin_src elisp
(setq org-cite-csl-styles-dir
      (concat
       (getenv "HOME")
       "/Nextcloud/documents/org/latex/citeproc-formatters/"))
#+end_src

**** Org Archive Location

#+begin_src elisp
(setq org-archive-location "archives/%s_archive::")
#+end_src

*** Download/capture for Org mode

#+begin_src elisp
(with-eval-after-load 'org
  (require 'org-download))
#+end_src

*** Org-download image width attribute tag

Added automatically when images are attached. Does not affect actual image dimensions, only how they are shown initially within Emacs.

#+begin_src elisp
(setq org-image-actual-width nil)
#+end_src

*** LaTeX classes for org mode with org-latex-classes

Helpful when editing LaTeX documents.

#+begin_src elisp
(with-eval-after-load 'ox-latex
(add-to-list 'org-latex-classes
             '("org-plain-latex"
               "\\documentclass{article}
           [NO-DEFAULT-PACKAGES]
           [PACKAGES]
           [EXTRA]"
               ("\\section{%s}" . "\\section*{%s}")
               ("\\subsection{%s}" . "\\subsection*{%s}")
               ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
               ("\\paragraph{%s}" . "\\paragraph*{%s}")
               ("\\subparagraph{%s}" . "\\subparagraph*{%s}"))))
#+end_src

*** A Not-Stupid Way to Archive Sections of Org Documents: Hierarchical Subtree Archival :org:archive:

By default, using the Org mode archive function 'org-archive-subtree-default' does not capture the higher-level headings a particular subheading was sitting under when it was archived, which makes a mess of the archive file that gets created. Use this instead!

**** Example and Reference :org:archive:

#+begin_example elisp
;; org-archive-subtree-hierarchical.el
;;
;; version 0.2
;; modified from https://lists.gnu.org/archive/html/emacs-orgmode/2014-08/msg00109.html
;; modified from https://stackoverflow.com/a/35475878/259187
;; In orgmode
;; * A
;; ** AA
;; *** AAA
;; ** AB
;; *** ABA
;; Archiving AA will remove the subtree from the original file and create
;; it like that in archive target:
;; * AA
;; ** AAA
;; And this give you
;; * A
;; ** AA
;; *** AAA
;;
;; Install file to your include path and include in your init file with:
;;
;;  (require 'org-archive-subtree-hierarchical)
;;  (setq org-archive-default-command 'org-archive-subtree-hierarchical)
;;
#+end_example

**** Source code of ~org-archive-subtree-hierarchical~ :org:archive:

#+begin_src elisp
(after! 'org
  (provide 'org-archive-subtree-hierarchical)
  (require 'org-archive)
  (defun org-archive-subtree-hierarchical--line-content-as-string ()
    "Returns the content of the current line as a string"
    (save-excursion
      (beginning-of-line)
      (buffer-substring-no-properties
       (line-beginning-position) (line-end-position))))

  (defun org-archive-subtree-hierarchical--org-child-list ()
    "This function returns all children of a heading as a list. "
    (interactive)
    (save-excursion
      ;; this only works with org-version > 8.0, since in previous
      ;; org-mode versions the function (org-outline-level) returns
      ;; gargabe when the point is not on a heading.
      (if (= (org-outline-level) 0)
          (outline-next-visible-heading 1)
        (org-goto-first-child))
      (let ((child-list (list (org-archive-subtree-hierarchical--line-content-as-string))))
        (while (org-goto-sibling)
          (setq child-list (cons (org-archive-subtree-hierarchical--line-content-as-string) child-list)))
        child-list)))

  (defun org-archive-subtree-hierarchical--org-struct-subtree ()
    "This function returns the tree structure in which a subtree belongs as a list."
    (interactive)
    (let ((archive-tree nil))
      (save-excursion
        (while (org-up-heading-safe)
          (let ((heading
                 (buffer-substring-no-properties
                  (line-beginning-position) (line-end-position))))
            (if (eq archive-tree nil)
                (setq archive-tree (list heading))
              (setq archive-tree (cons heading archive-tree))))))
      archive-tree))

  (defun org-archive-subtree-hierarchical ()
    "This function archives a subtree hierarchical"
    (interactive)
    (let ((org-tree (org-archive-subtree-hierarchical--org-struct-subtree))
          (this-buffer (current-buffer))
          (file (abbreviate-file-name
                 (or (buffer-file-name (buffer-base-buffer))
                     (error "No file associated to buffer")))))
      (save-excursion
        (setq location org-archive-location
              afile (car (org-archive--compute-location
                          (or (org-entry-get nil "ARCHIVE" 'inherit) location)))
              ;; heading (org-extract-archive-heading location)
              infile-p (equal file (abbreviate-file-name (or afile ""))))
        (unless afile
          (error "Invalid `org-archive-location'"))
        (if (> (length afile) 0)
            (setq newfile-p (not (file-exists-p afile))
                  visiting (find-buffer-visiting afile)
                  buffer (or visiting (find-file-noselect afile)))
          (setq buffer (current-buffer)))
        (unless buffer
          (error "Cannot access file \"%s\"" afile))
        (org-cut-subtree)
        (set-buffer buffer)
        (org-mode)
        (goto-char (point-min))
        (while (not (equal org-tree nil))
          (let ((child-list (org-archive-subtree-hierarchical--org-child-list)))
            (if (member (car org-tree) child-list)
                (progn
                  (search-forward (car org-tree) nil t)
                  (setq org-tree (cdr org-tree)))
              (progn
                (goto-char (point-max))
                (newline)
                (org-insert-struct org-tree)
                (setq org-tree nil)))))
        (newline)
        (org-yank)
        (when (not (eq this-buffer buffer))
          (save-buffer))
        (message "Subtree archived %s"
                 (concat "in file: " (abbreviate-file-name afile))))))

  (defun org-insert-struct (struct)
    "TODO"
    (interactive)
    (when struct
      (insert (car struct))
      (newline)
      (org-insert-struct (cdr struct))))

  (defun org-archive-subtree ()
    (org-archive-subtree-hierarchical)))
#+end_src

**** Change the Default Org Archive Function to be the Not-Stupid One :org:archive:

#+begin_src elisp
(after! 'org-archive
  (setq org-archive-default-command 'org-archive-subtree-hierarchical))
#+end_src

*** Custom Org Agenda files :faq:

Want files tracked in your agenda? Use the ~C-c [~ keybinding in each file to add them to your custom.el to be tracked via your agenda.

*** Org Mode Capture Templates Customization :org:templates:

**** default version

#+begin_example elisp
(("t" "Personal todo" entry (file+headline +org-capture-todo-file "Inbox")
  "* [ ] %?\n%i\n%a" :prepend t)
 ("n" "Personal notes" entry (file+headline +org-capture-notes-file "Inbox")
  "* %u %?\n%i\n%a" :prepend t)
 ("j" "Journal" entry (file+olp+datetree +org-capture-journal-file)
  "* %U %?\n%i\n%a" :prepend t)
 ("p" "Templates for projects")
 ("pt" "Project-local todo" entry
  (file+headline +org-capture-project-todo-file "Inbox") "* TODO %?\n%i\n%a"
  :prepend t)
 ("pn" "Project-local notes" entry
  (file+headline +org-capture-project-notes-file "Inbox") "* %U %?\n%i\n%a"
  :prepend t)
 ("pc" "Project-local changelog" entry
  (file+headline +org-capture-project-changelog-file "Unreleased")
  "* %U %?\n%i\n%a" :prepend t)
 ("o" "Centralized templates for projects")
 ("ot" "Project todo" entry #'+org-capture-central-project-todo-file
  "* TODO %?\n %i\n %a" :heading "Tasks" :prepend nil)
 ("on" "Project notes" entry #'+org-capture-central-project-notes-file
  "* %U %?\n %i\n %a" :heading "Notes" :prepend t)
 ("oc" "Project changelog" entry #'+org-capture-central-project-changelog-file
  "* %U %?\n %i\n %a" :heading "Changelog" :prepend t))
#+end_example

**** old version

#+begin_example elisp
(setq org-capture-templates
  '(("t" "Personal todo" entry (file+headline +org-capture-todo-file "Inbox") "* [ ] %?\n%i\n%a" :prepend t)
  ("n" "Personal notes" entry
  (file+headline +org-capture-notes-file "Inbox")
  "* %u %?\n%i\n%a" :prepend t)
  ("j" "Journal" entry
  (file+olp+datetree +org-capture-journal-file)
  "* %U %?\n%i\n%a" :prepend t)
  ("p" "Templates for projects")
  ("pt" "Project-local todo" entry
  (file+headline +org-capture-project-todo-file "Inbox")
  "* TODO %?\n%i\n%a" :prepend t)
  ("pn" "Project-local notes" entry
  (file+headline +org-capture-project-notes-file "Inbox")
  "* %U %?\n%i\n%a" :prepend t)
  ("pc" "Project-local changelog" entry
  (file+headline +org-capture-project-changelog-file "Unreleased")
  "* %U %?\n%i\n%a" :prepend t)
  ("o" "Centralized templates for projects")
  ("ot" "Project todo" entry #'+org-capture-central-project-todo-file "* TODO %?\n %i\n %a" :heading "Tasks" :prepend nil)
  ("on" "Project notes" entry #'+org-capture-central-project-notes-file "* %U %?\n %i\n %a" :heading "Notes" :prepend t)
  ("oc" "Project changelog" entry #'+org-capture-central-project-changelog-file "* %U %?\n %i\n %a" :heading "Changelog" :prepend t)))
#+end_src

**** TODO new version

Mon Mar 31 09:50:32 2025
Wed Jun  4 18:28:02 2025

#+begin_quote
  %a          Annotation, normally the link created with org-store-link.
  %A          Like %a, but prompt for the description part.
  %l          Like %a, but only insert the literal link.
  %L          Like %l, but without brackets (the link content itself).
#+end_quote

#+begin_quote
 :prepend            Normally newly captured information will be appended at
                     the target location (last child, last table line,
                     last list item...).  Setting this property will
                     change that.
#+end_quote

Mine:

#+begin_src elisp
(setq org-capture-templates
  '(("t" "Personal todo" entry (file+headline +org-capture-todo-file "Inbox") "* [ ] %?\n%i\n" :prepend t)
    ("n" "Personal notes" entry (file+headline +org-capture-notes-file "Inbox") "* %u %?\n%i\n" :prepend t)
    ("j" "Journal" entry (file+olp+datetree +org-capture-journal-file) "* %U %?\n%i\n" :prepend t)
    ("p" "Templates for projects")
    ("pt" "Project-local todo" entry (file+headline +org-capture-project-todo-file "Inbox") "* TODO %?\n%i\n%a" :prepend t)
    ("pn" "Project-local notes" entry (file+headline +org-capture-project-notes-file "Inbox") "* %U %?\n%i\n%a" :prepend t)
    ("pc" "Project-local changelog" entry (file+headline +org-capture-project-changelog-file "Unreleased") "* %U %?\n%i\n%a" :prepend t)
    ("o" "Centralized templates for projects")
    ("ot" "Project todo" entry #'+org-capture-central-project-todo-file "* TODO %?\n %i\n %a" :heading "Tasks" :prepend nil)
    ("on" "Project notes" entry #'+org-capture-central-project-notes-file "* %U %?\n %i\n %a" :heading "Notes" :prepend t)
    ("oc" "Project changelog" entry #'+org-capture-central-project-changelog-file "* %U %?\n %i\n %a" :heading "Changelog" :prepend t)))
#+end_src

From systemcrafters:

#+begin_example elisp
(defun dw/read-file-as-string (path)
  (with-temp-buffer
    (insert-file-contents path)
    (buffer-string)))
#+end_example


#+begin_example elisp
(setq org-capture-templates
  `(("t" "Tasks / Projects")
    ("tt" "Task" entry (file+olp "~/Projects/Code/emacs-from-scratch/OrgFiles/Tasks.org" "Inbox")
         "* TODO %?\n  %U\n  %a\n  %i" :empty-lines 1)
    ("ts" "Clocked Entry Subtask" entry (clock)
         "* TODO %?\n  %U\n  %a\n  %i" :empty-lines 1)

    ("j" "Journal Entries")
    ("jj" "Journal" entry
         (file+olp+datetree "~/Projects/Code/emacs-from-scratch/OrgFiles/Journal.org")
         "\n* %<%I:%M %p> - Journal :journal:\n\n%?\n\n"
         ;; ,(dw/read-file-as-string "~/Notes/Templates/Daily.org")
         :clock-in :clock-resume
         :empty-lines 1)
    ("jm" "Meeting" entry
         (file+olp+datetree "~/Projects/Code/emacs-from-scratch/OrgFiles/Journal.org")
         "* %<%I:%M %p> - %a :meetings:\n\n%?\n\n"
         :clock-in :clock-resume
         :empty-lines 1)

    ("w" "Workflows")
    ("we" "Checking Email" entry (file+olp+datetree ,(dw/get-todays-journal-file-name))
         "* Checking Email :email:\n\n%?" :clock-in :clock-resume :empty-lines 1)

    ("m" "Metrics Capture")
    ("mw" "Weight" table-line (file+headline "~/Projects/Code/emacs-from-scratch/OrgFiles/Metrics.org" "Weight")
     "| %U | %^{Weight} | %^{Notes} |" :kill-buffer t)))
#+end_example

#+begin_quote
Bindings straight to templates
#+end_quote

#+begin_src elisp
(define-key global-map (kbd "C-c j")
  (lambda () (interactive) (org-capture nil "j")))
#+end_src

Habit tracking

#+begin_example elisp
(require 'org-habit)
(add-to-list 'org-modules 'org-habit)
(setq org-habit-graph-column 60)
#+end_example

*** Vulpea Auto-Sync Org Roam v2 todos from dailies :org:roam:vulpea:

#+begin_src elisp
(after! 'org
  (use-package! vulpea
    :hook ((org-roam-db-autosync-mode . vulpea-db-autosync-enable))))
#+end_src

*** Tangle a single block at a time

From [[https://stackoverflow.com/a/39628921][joon]]:

#+begin_src elisp
(defun org-babel-tangle-block ()
  (interactive)
  (let ((current-prefix-arg '(4)))
    (call-interactively 'org-babel-tangle)))

(after! org
  (map! :map org-mode-map
        :prefix "C-c C-v"
        "t" #'org-babel-tangle-block
        "T" #'org-babel-tangle))
#+end_src

**** Tangle a single block from within the special edit menu

From [[https://stackoverflow.com/a/68962704][Dennis Proksch]]:

#+begin_src elisp
(defun org-babel-tangle-from-edit-special ()
    (interactive)
    (org-edit-src-exit)
    (let ((current-prefix-arg '(4)))
      (call-interactively 'org-babel-tangle))
    (org-edit-special))

(after! org
  (map! :map org-src-mode-map
        "<f9>" #'org-babel-tangle-from-edit-special))
#+end_src

Do this: put pointer in a code block -> m ' -> F9 to tangle.

*** Convert markdown buffer to org

#+begin_src elisp
(defun markdown-convert-buffer-to-org ()
  "Convert the current buffer's content from markdown to orgmode format
   and save it with the current buffer's file name but with .org extension."
  (interactive)
  (shell-command-on-region (point-min)
                           (point-max)
                           (format "pandoc -f markdown -t org -o %s"
                                   (concat (file-name-sans-extension
                                            (buffer-file-name)) ".org"))))
#+end_src

*** TODO Custom Command to Show Only DONE Tasks Today

Doesn't work
#+begin_example elisp
(setq org-agenda-custom-commands
      '(("d" "Tasks done today"
         ((agenda ""
                  ((org-agenda-span 'day)
                   (org-agenda-start-with-log-mode t)
                   (org-agenda-log-mode-items '(closed state))
                   ;;(org-agenda-archives-mode t)
                   ))))))
#+end_example

** nasm-mode

#+begin_src elisp
(add-to-list 'auto-mode-alist '("\\.\\(asm\\|s\\|S\\)$" . nasm-mode))
#+end_src

** Ascii Table

By [[https://www.emacswiki.org/emacs/Rick_Bielawski][Rick Bielawski]] ([[https://www.emacswiki.org/emacs/AsciiTable][EmacsWiki: Ascii Table]]):

#+begin_src elisp
  (defun ascii-table ()
    "Display basic ASCII table (0 thru 128)."
    (interactive)
    (switch-to-buffer "*ASCII*")
    (erase-buffer)
    (setq buffer-read-only nil)        ;; Not need to edit the content, just read mode (added)
    (local-set-key "q" 'bury-buffer)   ;; Nice to have the option to bury the buffer (added)
    (save-excursion (let ((i -1))
      (insert "ASCII characters 0 thru 127.\n\n")
      (insert " Hex  Dec  Char|  Hex  Dec  Char|  Hex  Dec  Char|  Hex  Dec  Char\n")
      (while (< i 31)
        (insert (format "%4x %4d %4s | %4x %4d %4s | %4x %4d %4s | %4x %4d %4s\n"
                        (setq i (+ 1  i)) i (single-key-description i)
                        (setq i (+ 32 i)) i (single-key-description i)
                        (setq i (+ 32 i)) i (single-key-description i)
                        (setq i (+ 32 i)) i (single-key-description i)))
        (setq i (- i 96))))))
#+end_src

** Emacs Relay Chat (~erc~) for Internet Relay Chat (IRC) :irc:

Set user information.

#+begin_src elisp
(setq erc-server "localhost"
      erc-nick "chuthepup"
      erc-user-full-name "Chu the Pup")
#+end_src

** Editing server (~edit-server~) for Emacs with ~edit-with-emacs~

#+begin_src elisp
(require 'edit-server)
(edit-server-start)
#+end_src

** Dictionary

#+begin_src elisp
(after! 'org
  (setq ispell-alternate-dictionary "/usr/share/dict"))
#+end_src

** ~auth-source-save-behavior~

#+begin_src elisp
(setq auth-source-save-behavior nil)
#+end_src

** ~nov.el~ for reading epub files in Emacs

This is a hook to activate the ~nov.el~ mode (nov-mode) whenever you open a file ending in ".epub" within Emacs.

#+begin_src elisp
(add-to-list 'auto-mode-alist '("\\.epub\\'" . nov-mode))
#+end_src

** ~dired~ directory editor (Emacs file manager) settings :dired:

*** Have Dired ask to back files up prior to overwriting them.

Make sure you know where your Emacs cache backup directory actually resides before putting this in your Emacs's initialization file (unless you use gio trash, which'll put your trash in $XDG_DATA_DIR/Trash/files).

#+begin_src elisp
;; Ask to back files up prior to overwriting them
(setq dired-backup-overwrite t)
#+end_src

*** Trash instead of delete :dired:

#+begin_src elisp
(setq delete-by-moving-to-trash t)
#+end_src

*** Dired listing style switches

**** Vanilla Emacs default

#+begin_src elisp :tangle no
(setq dired-listing-switches "-al")
#+end_src

**** DOOM Emacs Default

#+begin_src elisp :tangle no
(setq dired-listing-switches "-ahl -v --group-directories-first")
#+end_src

**** Mine

#+begin_src elisp
(setq dired-listing-switches "-hl -v --group-directories-first")
#+end_src

*** Dirvish

#+begin_src elisp
(after! dirvish
  ;; Hide dotfiles by default
  (setq dirvish-listing-switches "-hlv --group-directories-first")

  (defun dirvish-toggle-dotfiles ()
    "Toggle showing dotfiles in Dirvish."
    (interactive)
    (if (string-match-p "\\b-a\\b" dirvish-listing-switches)
        (setq dirvish-listing-switches "-hlv --group-directories-first") ; Hide dotfiles
      (setq dirvish-listing-switches "-ahlv --group-directories-first")) ; Show dotfiles
    (dirvish-refresh))

  (map! :map dirvish-mode-map
        "C-<escape>" #'dirvish-toggle-dotfiles))
#+end_src

** Enable active presence on Discord for Emacs

*WARNING*: This will tell anyone on your Discord your current activity status in Emacs—with a pretty hefty amount of detail as well. [[id:8f9bc104-87a1-4fa4-b624-a5ea64210b8a][Remember: you can do the following if you want to disable something]].

#+begin_src elisp
(use-package! elcord-mode
  :defer t
  :config
  (setq elcord-display-buffer-details nil
        elcord-display-line-numbers nil
        elcord-quiet t
        elcord-mode t))
#+end_src

** emms

#+begin_src elisp
(setq emms-source-beets-database "/run/media/root/grandarchive/root/audio/music/library.db")
#+end_src

** EPG: Letting Emacs query for GPG passwords

Allow Emacs to handle queries for gpg passwords.

#+begin_src elisp
(setq epg-pinentry-mode 'loopback)

(defun pinentry-emacs (desc prompt ok error)
  (let ((str (read-passwd (concat (replace-regexp-in-string "%22" "\""
                                  (replace-regexp-in-string "%0A" "\n" desc)) prompt ": ")))) str))
#+end_src

** Tramp :tramp:ssh:

*** Tramp FTP doesn't read my ~/.authinfo.gpg :tramp:ssh:

Ange-FTP defaults to =~/.netrc=  so you need to add this to your init script:

#+begin_src elisp
(setq ange-ftp-netrc-filename "~/.authinfo.gpg")
#+end_src

*** Tramp intregration with dirvish :tramp:ssh:dirvish:

#+begin_src elisp
(use-package tramp
  :config
  ;; Enable full-featured Dirvish over TRAMP on certain connections
  ;; https://www.gnu.org/software/tramp/#Improving-performance-of-asynchronous-remote-processes-1.
  (add-to-list 'tramp-connection-properties
               (list (regexp-quote "/ssh:chunix:")
                     "direct-async-process" t))
  ;; Tips to speed up connections
  (setq tramp-verbose 0
        tramp-chunksize 2000
        tramp-use-ssh-controlmaster-options nil))
#+end_src

** Palimpsest prog mode hook

#+begin_src elisp
(use-package! palimpsest-mode
  :hook (prog-mode . palimpsest-mode))
#+end_src

** Common Lisp

*** Common Lisp find file fix for Roswell compatibility :lisp:

#+begin_src elisp
(after! lisp-mode
  (defun +lisp/find-file-in-quicklisp ()
    "Find a file belonging to a library downloaded by Quicklisp."
    (interactive)
    (doom-project-find-file "~/.local/share/roswell/lisp/quicklisp/dists")))
#+end_src

*** ~roswell~ Lisp Sly helper :lisp:roswell:sly:repl:

#+begin_src elisp
(after! lisp-mode
  (load! (expand-file-name "~/.local/share/roswell/helper.el"))
  (setq inferior-lisp-program "ros dynamic-space-size=8000 -Q run"))
#+end_src

*** Common Lisp snippets for ya snippets (require)

#+begin_src elisp
(after! lisp-mode
  (use-package! common-lisp-snippets
  :defer t))
#+end_src

*** Sly completion fix :lisp:

#+begin_src elisp
(after! sly
  (setq sly-complete-symbol-function 'sly-flex-completions))
#+end_src

** C++

#+begin_src elisp
;;(setq c-syntactic-indentation nil)
#+end_src

** ~whisper~ Voice transcription (speech to text)

Personally, I can't get a model other than the ~base~ one to download. I'm an English speaker, so there's no translation services enabled.

The ~num-processors~ function is a part of base Emacs: [[https://www.gnu.org/software/emacs/manual/html_node/elisp/Process-Information.html#index-num_002dprocessors][GNU Emacs Manual 40.6 Process Information]].

#+begin_src elisp
(use-package whisper
  :config
  (setq whisper-install-directory "~/.config/emacs/.local/cache/"
        whisper-model "base"
        whisper-language "en"
        whisper-translate nil
        whisper-use-threads (/ (num-processors) 2))
        ;; turn off after 600 seconds of silence
        whisper-recording-timeout 600)
#+end_src

** company-tabnine
:PROPERTIES:
:ID:       bf00e5e6-33e9-4db7-ab2a-03118c2f2990
:END:

#+begin_src elisp
(after! company
  (setq +lsp-company-backends '(company-tabnine :separate company-capf company-yasnippet))
  (setq company-show-numbers t)
  (setq company-idle-delay 0))
#+end_src

** newline custom

#+begin_src elisp
(defun newline-after-comma-in-parens ()
  "Insert a newline after each comma within the parentheses of the current line and re-indent."
  (interactive)
  (save-excursion
    (let ((start (line-beginning-position))
          (end (line-end-position)))
      (goto-char start)
      (while (re-search-forward ",\\s-*" end t)
        (replace-match ",\n" t t))
      (indent-region start (line-end-position)))))

(map! :n "SPC p ," #'newline-after-comma-in-parens) ;; Bind it to a key, like `SPC p ,`
#+end_src

** hledger/ledger

*** Turn =ledger-mode= into =hledger-mode=

Figuratively, of course.

Requires hledger to be installed.

From https://hledger.org/editors.html#emacs

#+begin_src elisp
(require 'ob-hledger) ;; depends on org-contrib package
(setq ledger-binary-path "hledger.sh"
      ledger-mode-should-check-version nil
      ledger-report-auto-width nil
      ledger-report-links-in-register nil
      ledger-report-native-highlighting-arguments '("--color=always")
      ledger-default-date-string "%Y-%m-%d"
      ledger-source-directory (getenv "LEDGER_FILE")
      ledger-init-file nil
      ;; ledger-init-file-name "~/.ledgerrc"
      ;; ledger-init-file-name "~/.config/ledger/ledgerrc"
      ledger-accounts-file nil
      ledger-schedule-file nil
      ledger-payees-file nil)

(add-to-list 'auto-mode-alist '("\\.hledger\\'" . ledger-mode))
#+end_src

**** hledger.sh script

from https://hledger.org/editors.html#emacs
#+begin_src sh :mkdirp t :tangle ~/.local/bin/hledger.sh :shebang "#!/bin/sh" :eval no
# hledger.sh
# Kudos to acarrico for the original script.

# The script is contingent on ledger-default-date-string
# being set to "%Y-%m-%d", aka ISO date format.

iargs=("$@")
oargs=()
j=0;
date=;
for((i=0; i<${#iargs[@]}; ++i)); do
    case ${iargs[i]} in
        --date-format)
            # drop --date-format and the next arg
            i=$((i+1));
            ;;
        cleared) # for ledger-di
            splay-balance-at-point
            # convert "cleared" to "balance -N -C"
            oargs[j]=balance; oargs[j+1]=-N; oargs[j+2]=-C; j=$((j+3));
            ;;
        xact)
            # convert "xact" to "print --match"
            oargs[j]=print; oargs[j+1]=--match; j=$((j+2));
            # drop xact argument and stash the date argument
            i=$((i+1));
            date=${iargs[i]};
            ;;
        # NOTE: Reconciliation still doesn't work for other reasons
        #       so the following filters/conversions are unnecessary for now.
        # --sort) # for reconcilliation
        #     # drop --sort and the next arg
        #     i=$((i+1));
        #     ;;
        # --uncleared) # for reconcilliation
        #     # convert "--uncleared" to "--unmarked --pending"
        #     oargs[j]=--unmarked; oargs[j+1]=--pending; j=$((j+2))
        #     ;;
        ,*)
            # keep any other args:
            oargs[j]=${iargs[i]};
            j=$((j+1));
            ;;
    esac
done

if test "$date"
then
    # substitute the given date for the old date:
    hledger "${oargs[@]}" | sed "1s/....-..-../$date/"
else
    # echo "${oargs[@]}"
    hledger "${oargs[@]}"
fi
#+end_src

**** [[https://hledger.org/editors.html#misc][Misc]]

A helper to browse TODO tags in the journal:

#+begin_example elisp
(defun journal-todos nil (interactive) (lgrep "TODO:" "current.journal" "~/finance" nil))
#+end_example

**** Use strict account name checking (optional)

#+begin_src elisp
;; (after! 'ledger-mode
;;   (setq ledger-report-use-strict t))
#+end_src

**** custom hledger formatting scripts

#+begin_src elisp
(defvar chu/default-currency "$"
  "Default currency symbol used for formatting amounts.")

(defun chu/ledger-format-number-with-commas (num)
  "Format NUM with commas and two decimals (e.g., 1,234.56)."
  (let* ((str (format "%.2f" num))
         (parts (split-string str "\\."))
         (int-part (car parts))
         (dec-part (cadr parts))
         (int-with-commas
          (replace-regexp-in-string
           "\\B\\(\\d\\{3\\}\\)\\(\\(?:\\d\\{3\\}\\)*\\)" ",\\1" int-part)))
    (concat int-with-commas "." dec-part)))

(defun chu/format-usd (amount)
  "Format AMOUNT as a USD value with commas, 2 decimals, and no space before $."
  (let* ((num (abs amount))
         (sign (if (< amount 0) "-" ""))
         (formatted (chu/ledger-format-number-with-commas num)))
    (format "%s%s%s" sign chu/default-currency formatted)))

(defun chu/ledger-fill-1-xact ()
  "Fill one missing posting in the current transaction with formatted amount."
  (pcase-let* ((`(,total . ,missing-positions) (ledger-post-xact-total))
               (missing-amount (ledger-negate-commodity total))
               (amounts-balance (< (abs (car missing-amount)) 0.0001)))
    (pcase missing-positions
      ('() (unless amounts-balance
             (user-error "Postings do not balance, but no posting to fill")))
      (`(,missing-pos)
       (if amounts-balance
           (user-error "Missing amount but amounts balance already")
         (goto-char missing-pos)
         (insert "  " (chu/format-usd (car missing-amount)))
         (ledger-post-align-xact (point))))
      (_ (user-error "More than one posting with missing amount")))))

(with-eval-after-load 'ledger-mode
  (defun chu/ledger-post-fill (&optional beg end)
    "Fill missing posting amounts.

If region is active, process all transactions in region.
Otherwise, process only the current transaction."
    (interactive (if (use-region-p)
                     (list (region-beginning) (region-end))))
    (save-excursion
      (if (and beg end)
          ;; Region-based processing
          (progn
            (goto-char beg)
            (while (and (< (point) end)
                        (re-search-forward ledger-transaction-start-regexp end t))
              (goto-char (match-beginning 0))
              (chu/ledger-fill-1-xact)
              (ledger-next-xact)))
        ;; Single transaction fallback
        (chu/ledger-fill-1-xact)))))

;; Optional: keybinding for Doom Emacs
(with-eval-after-load 'ledger-mode
  (map! :map ledger-mode-map
        :localleader
        "f" #'chu/ledger-post-fill))
#+end_src

** Achievements in Emacs

#+begin_src elisp
(achievements-mode)
#+end_src

** =parrot-mode=

#+begin_src elisp
(parrot-mode)
#+end_src

** WSL2

*** Setup

**** =wsl_path.py= Setup

#+begin_src python :exec no :tangle no
import os
import sys

file_path = os.path.abspath(sys.argv[-1]).replace("\\", "/").replace("C:", "/mnt/c")

wsl_path_prefix = "//wsl$/Arch/"
if file_path.startswith(wsl_path_prefix):
    file_path = file_path.replace(wsl_path_prefix, "/")

command = "echo " + file_path.strip() + "| clip"
os.system(command)
#+end_src

**** wsl_emacs.py setup

#+begin_src python :exec no :tangle no
import sys
import subprocess
import os
import re

import win32gui


class WindowMgr:
    """Encapsulates some calls to the winapi for window management"""

    def __init__(self):
        """Constructor"""
        self._handle = None

    def find_window(self, class_name, window_name=None):
        """find a window by its class_name"""
        self._handle = win32gui.FindWindow(class_name, window_name)

    def _window_enum_callback(self, hwnd, wildcard):
        """Pass to win32gui.EnumWindows() to check all the opened windows"""
        if re.match(wildcard, str(win32gui.GetWindowText(hwnd))) is not None:
            self._handle = hwnd

    def find_window_wildcard(self, wildcard):
        """find a window whose title matches the wildcard regex"""
        self._handle = None
        win32gui.EnumWindows(self._window_enum_callback, wildcard)

    def set_foreground(self):
        """put the window in the foreground"""
        win32gui.SetForegroundWindow(self._handle)


if __name__ == "__main__":

    file_name = (
        '"' + sys.argv[1] + '"'
        if sys.argv[1].startswith("org-protocol")
        else os.path.abspath(sys.argv[1]).replace("\\", "/").replace("C:", "/mnt/c")
    )

    wsl_path_prefix = "//wsl$/Arch/"
    if file_name.startswith(wsl_path_prefix):
        file_name = file_name.replace(wsl_path_prefix, "/")

    command = " ".join(
        [
            "C:/Windows/System32/wsl.exe",
            "-d",
            "Arch",
            "emacsclient",
            "-n",
            file_name,
        ]
    )
    subprocess.Popen(command, shell=True)

    w = WindowMgr()
    w.find_window_wildcard(".*Doom Emac")
    w.set_foreground()
#+end_src

**** org-protocol registry setup

#+begin_src reg :exec no :tangle no
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\org-protocol]
@="URL:Org Protocol"
"URL Protocol"=""

[HKEY_CLASSES_ROOT\org-protocol\shell]

[HKEY_CLASSES_ROOT\org-protocol\shell\open]

[HKEY_CLASSES_ROOT\org-protocol\shell\open\command]
@="\"C:\\Users\\lain\\scoop\\apps\\python\\current\\pythonw.exe\" \"C:\\Portables.chu\\emacs-wsl\\wsl_emacs.py\" \"%1\""
#+end_src

*** TODO enable/disable WSL-specific settings

Since this is the 'navi' branch this is (will be?) enabled by default:

#+begin_src elisp :tangle no
;; (defvar IS-WSL t)
#+end_src

*** TODO open links in org-mode in emacs@wsl2 using windows apps

This is done by installing the [[https://github.com/wslutilities/wslu][wslu]] on your wsl2, and then you can config your org-mode by:

#+begin_src elisp
;; "Set org-file-apps based on the system type"
;; (when IS-WSL
  (setq org-file-apps '((remote . emacs)
                        (auto-mode . emacs)
                        (directory . emacs)
                        ("\\.mm\\'" . "wslview \"%s\"")
                        ("\\.x?html?\\'" . "wslview \"%s\"")
                        ("\\.pptx?\\'" . "wslview \"%s\"")
                        ("\\.xlsx?\\'" . "wslview \"%s\"")
                        ("\\.docx?\\'" . "wslview \"%s\"")
                        ("\\.pdf\\'" .  "wslview \"%s\"")))
  ;; need to set explorer for open weblinks and htmls seperately
  (setq browse-url-generic-program "/mnt/c/Program Files/Mozilla Firefox/firefox.exe")
;; )
#+end_src

*** TODO fix keyboard shortcut for C-shift-0

#+begin_src elisp
;; Windows 10 blocks Ctrl-Shift-0, So we using powertoy to cheat the system
;; when we press "C-)", it becomes "C->"
;; (cond (IS-WSL (map! "C->" #'sp-forward-slurp-sexp))
;;       (t (map! "C-)" #'sp-forward-slurp-sexp)))
#+end_src

*** TODO share clipboard between windows host and WSL2
:PROPERTIES:
:ID:       723b4e62-7315-4dd4-8515-7ca2748220b2
:END:

#+begin_src elisp
(defun win2wsl-clipped-image()
  "use powershell to save the clipped image to wsl and load it to xclip"
  (let* ((powershell "/mnt/c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe")
         (file-name "//wsl$/Arch/home/chu/tmp/clip_win2wsl.png")
         (file-name-wsl "~/tmp/clip_win2wsl.png")
         )
    (shell-command (concat powershell " -noprofile -command \"(Get-Clipboard -Format Image).Save(\\\"" file-name "\\\")\""))
    (call-process-shell-command (concat "xclip -selection clipboard -t image/png -i " file-name-wsl))
    )
  )
(advice-add 'org-download-clipboard :before #'win2wsl-clipped-image)
#+end_src

* Works Cited

** [[https://gergely.polonkai.eu/blog/2014/10/7/rounding-numbers-to-n-decimals-in-emacs.html][Rounding numbers to N decimals in Emacs]]

by Gergely Polonkai.

** https://blog.lazkani.io/posts/bookmark-with-org-capture/

** https://orgmode.org/manual/Capture-templates.html

** [[https://raw.githubusercontent.com/gilbertw1/emacs-literate-starter/master/emacs.org][DOOM Emacs Literate Config]]

By Gilbert. Thanks, Gilbert.

** [[https://github.com/alphapapa/unpackaged.el#ensure-blank-lines-between-headings-and-before-contents][alphapapa/unpackaged.el: A collection of useful Emacs Lisp code that isn't substantial enough to be packaged]]

This is where the '~ap/org-fix-blank-lines~' function was sourced from.

By alphapapa. Thanks, alphapapa.

** [[https://stackoverflow.com/a/35475878/259187][org-archive-subtree-hierarchical.el v0.2]]

By [[https://gist.github.com/kepi/2f4acc3cc93403c75fbba5684c5d852d][Kepi]]. Thanks, Kepi.

*** [[https://lists.gnu.org/archive/html/emacs-orgmode/2014-08/msg00109.html][org-archive-subtree-hierarchical.el v0.1]]

By [[https://lists.gnu.org/archive/html/emacs-orgmode/2014-08/msg00109.html][Florian Adamsky]]. Thanks, Florian Adamsky.

** System Crafters

Thanks, David!

*** [[https://www.youtube.com/watch?v=3-sLBaJAtew][Org Roam: The Best Way to Keep a Journal in Emacs - YouTube]]
