#+TITLE: Chu's Literate DOOM GNU Emacs Configuration
#+AUTHOR: chu the pup
#+DESCRIPTION: Chu's Literate Doom GNU Emacs configuration
#+PROPERTY: header-args :tangle yes
#+auto_tangle: t
* Preamble

Here's the deets:

** Org-mode babel tangle setup

There is a property defined on at the top of this file:

#+begin_example elisp
header-args :tangle yes
#+end_example

This tells Emacs to automatically tangle (include) all code blocks in this file when generating the code for the config file (~config.el~), unless the code block explicitly includes `:tangle no` as the above code block does (or if it is a quote or example block).

** Usage of quote and example blocks
:PROPERTIES:
:ID:       8f9bc104-87a1-4fa4-b624-a5ea64210b8a
:END:

What I am about to explain is typically done in order to debug the configuration on my end. However, the use of quote and example blocks also serves as a way of offering an on/off switch to certain blocks of "settings" (blocks beginning in "#+begin_something" and ending in "#+end_something"):

#+begin_quote
#+begin_example
...
#+end_example
#+end_quote

...or just delete it entirely if you don't want or need the feature / setting, for example, if you want to disable *[[id:a948faf0-c278-4481-bd1b-c857644a4c90][the active Discord presence support plugin for Emacs that I have turned on by default]]*.

I try to keep the ones seen here (as in, in this configuration) limited to settings saved for reference, debugging, or other posterity purposes, rather than leaving behind a bunch of crud and bug fixes that are no longer necessary.

* ~config.el~ lexical binding

#+begin_src elisp
;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-
#+end_src

* DOOM Emacs Documentation

Doom exposes five (optional) variables for controlling fonts in Doom. Here are the three important ones:

+ `doom-font'

+ `doom-variable-pitch-font'

+ `doom-big-font' -- used for `doom-big-font-mode'; use this for presentations or streaming.

They all accept either a font-spec, font string ("Input Mono-12"), or xlfd font string. You generally only need these two:

#+begin_example
(setq doom-font (font-spec :family "monospace" :size 12 :weight 'semi-light)
#+end_example

#+begin_example
(setq doom-variable-pitch-font (font-spec :family "sans" :size 13))
#+end_example

If you're having issues regarding fonts, you may want to [[id:24408296-5370-4dbf-a52f-f1afe865ceb5][stop Emacs from loading your Xresources file.]]

There are two ways to load a theme. Both assume the theme is installed and available. You can either set `doom-theme' or manually load a theme with the `load-theme' function. This is the default:

#+begin_example elisp
(setq doom-theme 'doom-one)
#+end_example

Here are some additional functions/macros that could help you configure Doom Emacs:

- `load!' for loading external *.el files relative to this one

- `use-package!' for configuring packages

- `after!' for running code after a package has loaded

- `add-load-path!' for adding directories to the `load-path', relative to
  this file. Emacs searches the `load-path' when you load packages with
  `require' or `use-package'.

- `map!' for binding new keys

To get information about any of these functions/macros, move the cursor over the highlighted symbol at press 'K' (non-evil users must press 'C-c c k'). This will open documentation for it, including demos of how they are used.

You can also try 'gd' (or 'C-c c d') to jump to their definition and see how they are implemented.

Place your private configuration here! Remember, you do not need to run 'doom sync' after modifying this file!

Some functionality uses this to identify you, e.g. GPG configuration, email clients, file templates and snippets.

#+begin_example elisp
(setq user-full-name "John Doe"
      user-mail-address "example@donut.arpa")
#+end_example

* Config
** Private Configuration

#+begin_src elisp :results none
(setq user-full-name "chu the pup"
      user-mail-address "chufilthymutt@gmail.com")
#+end_src

** Visual Changes
*** Inhibit Xresources being loaded by Emacs

#+begin_src elisp
(setq inhibit-x-resources t) ; inhibit .xresources file from being loaded on emacs init
#+end_src

*** Fix alpha transparency issues

Sometimes Emacs has issues with transparency. In my case, it goes unusably transparent if I make use of an Xresources file.

You can specify frames to use different levels of transparency depending on whether or not you have Emacs focused (active) or if you've clicked off to another application (inactive).

#+begin_example elisp
(set-frame-parameter (selected-frame) 'alpha '(<active> . <inactive>))
#+end_example

Or you can just use one number, as so:

#+begin_example elisp
(set-frame-parameter (selected-frame) 'alpha <both>)
#+end_example

Here's the settings I currently use:

Set current Emacs frame's opacity to 100%:

#+begin_src elisp :results none
(set-frame-parameter (selected-frame) 'alpha 100)
#+end_src

Set all Emacs frames opacity from this point on to 100%:

#+begin_src elisp :results none
(add-to-list 'default-frame-alist '(alpha 100))
#+end_src

Set Emacs's background opacity to 92%:

#+begin_src elisp :results none
(set-frame-parameter nil 'alpha-background 92)
#+end_src

Set all Emacs frames from this point on to have a background opacity of 92%:

#+begin_src elisp :results none
(add-to-list 'default-frame-alist '(alpha-background . 92))
#+end_src

from [[https://www.emacswiki.org/emacs/TransparentEmacs][EmacsWiki: Transparent Emacs]]

You may also wish to [[id:24408296-5370-4dbf-a52f-f1afe865ceb5][disable Emacs loading your Xresources file.]]

**** Font

I use the default LARBS monospace font instead of Fira Mono for consistency's sake.

#+begin_src elisp
(setq doom-font (font-spec :family "Mono" :size 12))
#+end_src

The following ensures correct font size without affecting the font used:

#+begin_example elisp
(setq doom-font (font-spec :size 12))
#+end_example

You may also wish to [[id:24408296-5370-4dbf-a52f-f1afe865ceb5][disable Emacs loading your Xresources file.]]

**** Temporarily convert images that Emacs cannot otherwise display

This will Set Emacs to convert images if they are going to be shown in the GUI. It detects when Emacs is unable to display the image due to lack of compatibility and temporarily converts it, pushing the converted version into memory during display (it gets cleaned up by the garbage collector).

Note: This is a soft dependency of random-splash-image; in turn, you risk being unable to display certain image file types (notably .webp files) if this is disabled.

#+begin_src elisp
(setq image-use-external-converter t)
#+end_src

**** Random Splash Images

***** Enable random-splash-image

For the plugin 'random-splash-image' which displays a random splash image on each Emacs startup.

#+begin_src elisp
(require 'random-splash-image)
#+end_src

***** Tell random-splash-image what directory to look for images in.

Example:

#+begin_example elisp
(setq random-splash-image-dir
      (concat
       (getenv "HOME")
       "/.local/share/random-splash-image-dir/example/memes/"))
#+end_example

I use a more specific one at the moment.

#+begin_src elisp
(setq random-splash-image-dir
      (concat
       (getenv "HOME")
       "/.local/share/random-splash-image-dir/chosen-splash-images/src/"))
#+end_src

***** IDEA How to set multiple directories for random-splash-image

I don't know how to do this yet.

**** Set a random splash image on Emacs startup

#+begin_src elisp
(with-eval-after-load 'random-splash-image
  (random-splash-image-set))
#+end_src

**** Toggle line numbers off by default

You can toggle them back on, turn them to a "relative line number" mode, and back off again with ~SPC t l~ (lowercase ~L~).

#+begin_src elisp :results none
(setq display-line-numbers nil)
#+end_src

*** Alpha background transparency function :function:

Requires a compositor.

[[https://kristofferbalintona.me/posts/202206071000/][True Emacs Transparency | Kristoffer Balintona]]

The original by kb:

#+begin_src elisp :tangle no
(defun kb/toggle-window-transparency ()
  "Toggle transparency."
  (interactive)
  (let ((alpha-transparency 85))
    (pcase (frame-parameter nil 'alpha-background)
      (alpha-transparency (set-frame-parameter nil 'alpha-background 100))
      (t (set-frame-parameter nil 'alpha-background alpha-transparency)))))
#+end_src


#+begin_src elisp :results none
(defun toggle-transparency ()
  "Toggle TOTAL EMACS X11 transparency. Might need to be called a couple of times in a row to work."
  (interactive)
  (let ((alpha (frame-parameter nil 'alpha)))
    (if (eq
     (if (numberp alpha)
         alpha
       (cdr alpha)) ; may also be nil
     100)
    (set-frame-parameter nil 'alpha '(85 . 50))
      (set-frame-parameter nil 'alpha '(100 . 100)))))
#+end_src

#+begin_src elisp :results none
(defun toggle-background-transparency ()
  "Toggle background transparency, wherein text and other elements in frame are still displayed but a background isn't."
  (interactive)
  (if (get 'toggle-background-transparency 'state)
      (progn
        (set-frame-parameter nil 'alpha-background 100)
        (put 'toggle-background-transparency 'state nil))
    (progn
      (set-frame-parameter nil 'alpha-background 75)
      (put 'toggle-background-transparency 'state t))))
#+end_src

** Org-Mode :org:
*** org TODO state hiding

Write TODO state changes into LOGBOOK drawer. [[https://stackoverflow.com/a/63798475][Thanks, LeeRuns (stackoverflow.com)]].

This helps keep Org files tidier and cleaner in the case of recurring / looping tasks. You can fold them, whereas by default, the change in TODO state (e.g. from TODO -> DONE) create separate logs.

#+begin_src elisp
(setq org-log-into-drawer "LOGBOOK")
#+end_src

*** Org Babel Auto-Tangle

For the package org-babel-auto-tangle (see packages.org).

#+begin_src elisp
(add-hook 'org-mode-hook 'org-auto-tangle-mode)
#+end_src

*** Hook load fragtog

#+begin_src elisp
(add-hook 'org-mode-hook 'org-fragtog-mode)
#+end_src

*** Custom org-todo-keywords

#+begin_src elisp
(setq org-todo-keywords
       '((sequence "TODO(t)" "PROJ(p)" "LOOP(r)" "STRT(s)" "WAIT(w)" "HOLD(h)" "HABIT(H)" "IDEA(i)" "|" "DONE(d)" "KILL(k)")
         (sequence "[ ](T)" "[-](S)" "[?](W)" "|" "[X](D)")
         (sequence "|" "OKAY(o)" "YES(y)" "NO(n)")))
#+end_src

*** Ensure blank lines between headings and before contents

Ensure that blank lines exist between headings and between headings and their contents.  With prefix, operate on whole buffer.  Ensures that blank lines exist after each headings's drawers.

For those who prefer to maintain blank lines between headings, this makes it easy to automatically add them where necessary, to a subtree or the whole buffer. It also adds blank lines after drawers. Works well with ~org-return-dwim~.

#+BEGIN_SRC elisp
  ;;;###autoload
  (defun unpackaged/org-fix-blank-lines (&optional prefix)
    "Ensure that blank lines exist between headings and between headings and their contents.
  With prefix, operate on whole buffer. Ensures that blank lines
  exist after each headings's drawers."
    (interactive "P")
    (org-map-entries (lambda ()
                       (org-with-wide-buffer
                        ;; `org-map-entries' narrows the buffer, which prevents us from seeing
                        ;; newlines before the current heading, so we do this part widened.
                        (while (not (looking-back "\n\n" nil))
                          ;; Insert blank lines before heading.
                          (insert "\n")))
                       (let ((end (org-entry-end-position)))
                         ;; Insert blank lines before entry content
                         (forward-line)
                         (while (and (org-at-planning-p)
                                     (< (point) (point-max)))
                           ;; Skip planning lines
                           (forward-line))
                         (while (re-search-forward org-drawer-regexp end t)
                           ;; Skip drawers. You might think that `org-at-drawer-p' would suffice, but
                           ;; for some reason it doesn't work correctly when operating on hidden text.
                           ;; This works, taken from `org-agenda-get-some-entry-text'.
                           (re-search-forward "^[ \t]*:END:.*\n?" end t)
                           (goto-char (match-end 0)))
                         (unless (or (= (point) (point-max))
                                     (org-at-heading-p)
                                     (looking-at-p "\n"))
                           (insert "\n"))))
                     t (if prefix
                           nil
                         'tree)))
#+END_SRC

by [[https://github.com/alphapapa/unpackaged.el#ensure-blank-lines-between-headings-and-before-contents][Alphapapa]]

*** Custom org directories and files :org:

If you use `org' and don't want your org files in the default location below, change `org-directory'. It must be set before org loads!

**** Custom org root directory :org:

The following will vary, so change it to be whatever your org root directory is/what you want it to be.

I use a directory that I sync between computers with a nextcloud server I run but you don't necessarily have to do that.

#+begin_src elisp
(after! 'org
  (setq org-directory
        (concat
         (getenv "HOME")
        "/nextcloud/documents/org/")))
#+end_src

#+RESULTS:

**** Custom org bookmark directory :org:

The following will vary, so change it to be whatever your bookmarks file is/what you want it to be.

I use a document that I track with org roam but you don't necessarily have to do that.

#+begin_src elisp
(with-eval-after-load 'org
  (setq +org-capture-bookmarks-file
        (concat
         (getenv "HOME")
         "/nextcloud/documents/org/roam/20221004090130-bookmarks.org")))
#+end_src

**** Custom org agenda files :org:

#+begin_src elisp
(setq org-agenda-files
      '("/home/chu/nextcloud/documents/org/roam/20220726210347-important_dates.org"
        "/home/chu/nextcloud/documents/org/roam/20221004221831-todo.org"
        "/home/chu/nextcloud/documents/org/roam/20220823133456-precalculus_algebra.org"
        "/home/chu/nextcloud/documents/org/roam/20220826102105-chem_1115.org"
        "/home/chu/nextcloud/documents/org/roam/20221004222241-notes.org"
        "/home/chu/nextcloud/documents/org/roam/20221004222237-journal.org"
        "/home/chu/nextcloud/documents/org/roam/20221004222234-projects.org"
        "/home/chu/nextcloud/documents/org/roam/20220822103211-engl_1030.org"
        "/home/chu/nextcloud/documents/org/roam/20221002161631-my_conlang.org"))
#+end_src

Usually, you just set these using `org-agenda-file-to-front`

**** Custom org journal file location :org:

You know the gist by now--change this to whatever you want your file to be.

#+begin_src elisp
(with-eval-after-load 'org
  (setq +org-capture-journal-file
        (concat
         (getenv "HOME")
         "/nextcloud/documents/org/roam/20221004222230-journal.org")))
#+end_src

**** Custom org notes file location :org:

#+begin_src elisp
(with-eval-after-load 'org
  (setq +org-capture-notes-file
        (concat
         (getenv "HOME")
         "/nextcloud/documents/org/roam/20221004222235-notes.org")))
#+end_src

**** Custom org projects file location :org:

#+begin_src elisp
(with-eval-after-load 'org
  (setq +org-capture-projects-file
        (concat
         (getenv "HOME")
         "/nextcloud/documents/org/roam/20221004222226-projects.org")))
#+end_src

**** Custom org todo file location :org:

I primarily use a "todo" file rather than an "agenda" file, for agenda ("TODO") items.

#+begin_src elisp
(with-eval-after-load 'org
  (setq +org-capture-todo-file
        (concat
         (getenv "HOME")
         "/nextcloud/documents/org/roam/20221004221829-todo.org")))
#+end_src

**** Org roam v2 directories and files :org:roam:

#+begin_src elisp
(with-eval-after-load 'org
  (setq org-roam-directory
        (concat
         (getenv "HOME")
         "/nextcloud/documents/org/roam/")))
#+end_src

**** Org roam v2 dailies directory :org:roam:

Path to daily-notes. This path is relative to org-roam-directory.

#+begin_src elisp
(setq org-roam-dailies-directory "daily/")
#+end_src

**** Org roam v2 dailies capture template :org:roam:

#+begin_src elisp
(setq org-roam-dailies-capture-templates
      '(("d" "default" entry
         "* %?"
         :target (file+head "%<%Y-%m-%d>.org"
                            "#+title: %<%Y-%m-%d>\n"))))
#+end_src

**** org-roam-protocol test :org:roam:protocols:

#+begin_src elisp
(require 'org-roam-protocol)
#+end_src

**** org-roam-export test :org:roam:

#+begin_src elisp
(require 'org-roam-export)
#+end_src

**** Org id custom id location :org:

#+begin_src elisp
(setq org-id-locations-file
      (concat
       (getenv "HOME")
       "/nextcloud/documents/org/.orgids"))
#+end_src

**** Org-attach custom directory :org:

#+begin_src elisp
(setq org-attach-id-dir
      (concat
       (getenv "HOME")
       "/nextcloud/documents/org/.attach/"))
#+end_src

**** Org-Cite (oc.el) :org:cite:

***** Org-Cite (oc.el) bibliography location :org:cite:bib:

#+begin_src elisp
(setq org-cite-global-bibliography
       (list
        (concat
         (getenv "HOME")
         "/nextcloud/documents/org/roam/bib.bib")))
#+end_src

See also [[https://orgmode.org/manual/Citations.html#Citations-1][the org mode manual section on org-cite, the citation module that is native to emacs org mode]] in order to specify per-file bibliography files with .bib or .json files.

***** Org-Cite (oc.el) CiteProc formatter file directory location :org:cite:citeproc:

Citation Style Language (CSL) files can be used with org-cite.

#+begin_src elisp
(setq org-cite-csl-styles-dir
      (concat
       (getenv "HOME")
       "/nextcloud/documents/org/latex/citeproc-formatters/"))
#+end_src

*** Download/capture for Org mode

#+begin_src elisp
(with-eval-after-load 'org
  (require 'org-download)
  (add-hook 'dired-mode-hook 'org-download-enable))
#+end_src

*** Org-download image width attribute tag

Added automatically when images are attached. Does not affect actual image dimensions, only how they are shown initially within Emacs.

#+begin_src elisp
(setq org-image-actual-width nil)
#+end_src

#+RESULTS:

*** LaTeX classes for org mode with org-latex-classes

Helpful when editing LaTeX documents.

#+begin_src elisp
(with-eval-after-load 'ox-latex
(add-to-list 'org-latex-classes
             '("org-plain-latex"
               "\\documentclass{article}
           [NO-DEFAULT-PACKAGES]
           [PACKAGES]
           [EXTRA]"
               ("\\section{%s}" . "\\section*{%s}")
               ("\\subsection{%s}" . "\\subsection*{%s}")
               ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
               ("\\paragraph{%s}" . "\\paragraph*{%s}")
               ("\\subparagraph{%s}" . "\\subparagraph*{%s}"))))
#+end_src

*** A Not-Stupid Way to Archive Sections of Org Documents: Hierarchical Subtree Archival :org:archive:

By default, using the Org mode archive function 'org-archive-subtree-default' does not capture the higher-level headings a particular subheading was sitting under when it was archived, which makes a mess of the archive file that gets created. Use this instead!

**** Example and Reference :org:archive:

#+begin_example elisp
;; org-archive-subtree-hierarchical.el
;;
;; version 0.2
;; modified from https://lists.gnu.org/archive/html/emacs-orgmode/2014-08/msg00109.html
;; modified from https://stackoverflow.com/a/35475878/259187
;; In orgmode
;; * A
;; ** AA
;; *** AAA
;; ** AB
;; *** ABA
;; Archiving AA will remove the subtree from the original file and create
;; it like that in archive target:
;; * AA
;; ** AAA
;; And this give you
;; * A
;; ** AA
;; *** AAA
;;
;; Install file to your include path and include in your init file with:
;;
;;  (require 'org-archive-subtree-hierarchical)
;;  (setq org-archive-default-command 'org-archive-subtree-hierarchical)
;;
#+end_example

**** Source code of ~org-archive-subtree-hierarchical~ :org:archive:

#+begin_src elisp :results none
(after! 'org
  (provide 'org-archive-subtree-hierarchical)
  (require 'org-archive)
  (defun org-archive-subtree-hierarchical--line-content-as-string ()
    "Returns the content of the current line as a string"
    (save-excursion
      (beginning-of-line)
      (buffer-substring-no-properties
       (line-beginning-position) (line-end-position))))
  (defun org-archive-subtree-hierarchical--org-child-list ()
    "This function returns all children of a heading as a list. "
    (interactive)
    (save-excursion
      ;; this only works with org-version > 8.0, since in previous
      ;; org-mode versions the function (org-outline-level) returns
      ;; gargabe when the point is not on a heading.
      (if (= (org-outline-level) 0)
          (outline-next-visible-heading 1)
        (org-goto-first-child))
      (let ((child-list (list (org-archive-subtree-hierarchical--line-content-as-string))))
        (while (org-goto-sibling)
          (setq child-list (cons (org-archive-subtree-hierarchical--line-content-as-string) child-list)))
        child-list)))
  (defun org-archive-subtree-hierarchical--org-struct-subtree ()
    "This function returns the tree structure in which a subtree belongs as a list."
    (interactive)
    (let ((archive-tree nil))
      (save-excursion
        (while (org-up-heading-safe)
          (let ((heading
                 (buffer-substring-no-properties
                  (line-beginning-position) (line-end-position))))
            (if (eq archive-tree nil)
                (setq archive-tree (list heading))
              (setq archive-tree (cons heading archive-tree))))))
      archive-tree))
  (defun org-archive-subtree-hierarchical ()
    "This function archives a subtree hierarchical"
    (interactive)
    (let ((org-tree (org-archive-subtree-hierarchical--org-struct-subtree))
          (this-buffer (current-buffer))
          (file (abbreviate-file-name
                 (or (buffer-file-name (buffer-base-buffer))
                     (error "No file associated to buffer")))))
      (save-excursion
        (setq location org-archive-location
              afile (car (org-archive--compute-location
                          (or (org-entry-get nil "ARCHIVE" 'inherit) location)))
              ;; heading (org-extract-archive-heading location)
              infile-p (equal file (abbreviate-file-name (or afile ""))))
        (unless afile
          (error "Invalid `org-archive-location'"))
        (if (> (length afile) 0)
            (setq newfile-p (not (file-exists-p afile))
                  visiting (find-buffer-visiting afile)
                  buffer (or visiting (find-file-noselect afile)))
          (setq buffer (current-buffer)))
        (unless buffer
          (error "Cannot access file \"%s\"" afile))
        (org-cut-subtree)
        (set-buffer buffer)
        (org-mode)
        (goto-char (point-min))
        (while (not (equal org-tree nil))
          (let ((child-list (org-archive-subtree-hierarchical--org-child-list)))
            (if (member (car org-tree) child-list)
                (progn
                  (search-forward (car org-tree) nil t)
                  (setq org-tree (cdr org-tree)))
              (progn
                (goto-char (point-max))
                (newline)
                (org-insert-struct org-tree)
                (setq org-tree nil)))))
        (newline)
        (org-yank)
        (when (not (eq this-buffer buffer))
          (save-buffer))
        (message "Subtree archived %s"
                 (concat "in file: " (abbreviate-file-name afile))))))
  (defun org-insert-struct (struct)
    "TODO"
    (interactive)
    (when struct
      (insert (car struct))
      (newline)
      (org-insert-struct (cdr struct))))
  (defun org-archive-subtree ()
    (org-archive-subtree-hierarchical)))
#+end_src

**** Change the Default Org Archive Function to be the Not-Stupid One :org:archive:

#+begin_src elisp :results none
(after! 'org-archive
  (setq org-archive-default-command 'org-archive-subtree-hierarchical))
#+end_src

*** Custom Org Agenda files :faq:

Want files tracked in your agenda? Use the ~C-c [~ keybinding in each file to add them to your custom.el to be tracked via your agenda.

*** Org Tanglesync :org:tanglesync:

#+begin_src elisp :results none
;; (use-package! org-tanglesync
;;   :hook ((org-mode . org-tanglesync-mode)
;;          ;; enable watch-mode globally:
;;          ((prog-mode text-mode) . org-tanglesync-watch-mode))
;;   :custom (org-tanglesync-watch-files '("example.org"))
;;   :bind
;;   (( "C-c M-i" . org-tanglesync-process-buffer-interactive)
;;    ( "C-c M-a" . org-tanglesync-process-buffer-automatic)))
#+end_src

*** Org Mode Capture Templates Customization :org:templates:
#+begin_src elisp :results none
(after! 'org
  (setq org-capture-templates
    (("t" "Personal todo" entry
      (file+headline +org-capture-todo-file "Inbox")
    "* [ ] %?\n%i\n%a" :prepend t)
    ("n" "Personal notes" entry
    (file+headline +org-capture-notes-file "Inbox")
    "* %u %?\n%i\n%a" :prepend t)
    ("j" "Journal" entry
    (file+olp+datetree +org-capture-journal-file)
    "* %U %?\n%i\n%a" :prepend t)
    ("p" "Templates for projects")
    ("pt" "Project-local todo" entry
    (file+headline +org-capture-project-todo-file "Inbox")
    "* TODO %?\n%i\n%a" :prepend t)
    ("pn" "Project-local notes" entry
    (file+headline +org-capture-project-notes-file "Inbox")
    "* %U %?\n%i\n%a" :prepend t)
    ("pc" "Project-local changelog" entry
    (file+headline +org-capture-project-changelog-file "Unreleased")
    "* %U %?\n%i\n%a" :prepend t)
    ("o" "Centralized templates for projects")
    ("ot" "Project todo" entry #'+org-capture-central-project-todo-file "* TODO %?\n %i\n %a" :heading "Tasks" :prepend nil)
    ("on" "Project notes" entry #'+org-capture-central-project-notes-file "* %U %?\n %i\n %a" :heading "Notes" :prepend t)
    ("oc" "Project changelog" entry #'+org-capture-central-project-changelog-file "* %U %?\n %i\n %a" :heading "Changelog" :prepend t))))
#+end_src

*** Vulpea Auto-Sync Org Roam v2 todos from dailies :org:roam:vulpea:

#+begin_src elisp :results none
(after! 'org
  (use-package! vulpea
    :hook ((org-roam-db-autosync-mode . vulpea-db-autosync-enable))))
#+end_src

*** Procedure to tangle a single block at a time

From [[https://stackoverflow.com/a/39628921][joon]]:

#+begin_src elisp :results none
(defun org-babel-tangle-block ()
  (interactive)
  (let ((current-prefix-arg '(4)))
    (call-interactively 'org-babel-tangle)))

(after! org
  (map! :map org-mode-map
        :prefix "C-c C-v"
        "t" #'org-babel-tangle-block
        "T" #'org-babel-tangle))
#+end_src

**** Tangle a single block from within the special edit menu

From [[https://stackoverflow.com/a/68962704][Dennis Proksch]]:

#+begin_src elisp :results none
(defun org-babel-tangle-from-edit-special ()
    (interactive)
    (org-edit-src-exit)
    (let ((current-prefix-arg '(4)))
      (call-interactively 'org-babel-tangle))
    (org-edit-special))

(after! org
  (map! :map org-src-mode-map
        "<f9>" #'org-babel-tangle-from-edit-special))
#+end_src

Do this:
put pointer in a code block -> m ' -> F9
to tangle.

** Emacs Relay Chat (~erc~) for Internet Relay Chat (IRC) :irc:

Set user information.

#+begin_src elisp
(setq erc-server "localhost"
      erc-nick "chuthepup"
      erc-user-full-name "Chu the Pup")
#+end_src

** Editing server (~edit-server~) for Emacs with ~edit-with-emacs~
#+begin_src elisp
(require 'edit-server)
(edit-server-start)
#+end_src

** Dictionary

#+begin_src elisp :results none
(after! 'org
  (setq ispell-alternate-dictionary "/usr/share/dict"))
#+end_src

** ~auth-source-save-behavior~

#+begin_src elisp
(setq auth-source-save-behavior nil)
#+end_src

** ~nov.el~ for reading epub files in Emacs
:PROPERTIES:
:ID:       246c5efa-98ea-4285-b52a-39fbb914ea9f
:END:

This is a hook to activate the ~nov.el~ mode (nov-mode) whenever you open a file ending in ".epub" within Emacs.

#+begin_src elisp :results none
(add-to-list 'auto-mode-alist '("\\.epub\\'" . nov-mode))
#+end_src

** ~dired~ director editor (Emacs file manager) settings :dired:

Have Dired ask to back files up prior to overwriting them.

Make sure you know where your Emacs cache backup directory actually resides before putting this in your Emacs's initialization file (unless you use gio trash, which'll put your trash in $XDG_DATA_DIR/Trash/files)

#+begin_src elisp
(setq dired-backup-overwrite t)
#+end_src

*** dired-rsync :dired:rsync:

**** dired-rsync-skip-newer custom rsync function :dired:custom:rsync:

#+begin_src elisp
;; (defun dired-rsync-skip-newer (dest)
;;   "Asynchronously copy files in dired to `DEST' using rsync
;; set to resolve symlinks, skip files that are newer in `DEST',
;; and to run in archive mode."
;;   (interactive
;;    (list (read-file-name "rsync to: " (dired-dwim-target-directory)
;;                               nil nil nil 'file-directory-p)))
;;   (let ((dired-rsync-options "-aLuz --info=progress2"))
;;         (dired-rsync dest)))
#+end_src

**** ~dired-rsync-skip-newer~ binding map :dired:binds:custom:rsync:

#+begin_src elisp
;; (after! dired
;;   (map! :map dired-mode-map
;;         :prefix "C-c C-d"
;;         "C-r" #'dired-rsync-skip-newer))
#+end_src

*** Trash instead of delete :dired:

#+begin_src elisp
(setq delete-by-moving-to-trash t)
#+end_src
*** Bindings
#+begin_src elisp
(map! :map dired-mode-map "<normal-state> l" #'dired-find-file)
(map! :map dired-mode-map "<normal-state> h" #'dired-up-directory)
(map! :map dirvish-mode-map "<normal-state> q" #'dirvish-quit)
(map! :map general-override-mode-map "<normal-state> SPC o _" #'dirvish)
#+end_src

#+RESULTS:

** ~abbrev-mode~
:PROPERTIES:
:ID:       573045ef-062a-4bc9-94c8-d9a3f5c9c9d0
:END:

The mode in the abbrev-mode package allows for user-defined abbreviations that get expanded during typing. I have them turn on when in Org mode or Text mode and have them off otherwise.

#+begin_src elisp :results none
(use-package! abbrev-mode
  :hook (org-mode . abbrev-mode)
        (text-mode . abbrev-mode))
#+end_src

** Projectile project management
:PROPERTIES:
:ID:       cb42f656-6a3f-45c3-9eeb-0298b829010d
:END:
*** Projectile:  don't look for .ccls_cache

I prefer ".git".

#+begin_src elisp :results none
;; (after! 'projectile
  ;; (setq projectile-project-root-files-bottom-up '(".project"))
  ;; )
#+end_src

*** Projectile don't look for Makefile

#+begin_src elisp :results none
;; (setq projectile-project-root-files-top-down-recurring '(".project"))
#+end_src

*** Correct Projectile sub directory detection

#+begin_src elisp :results none
;; (setq projectile-switch-project-action #'projectile-find-dir)
;; (setq projectile-find-dir-includes-top-level t)
#+end_src

*** Disable automatic project detection as a whole

#+begin_src elisp
(setq projectile-project-root-functions nil)
#+end_src

*** RipGrep "rg" fast search to handle Projectile project files

Use the faster searcher to handle project files: ripgrep "rg"

#+begin_src elisp
(when (and (not (executable-find "fd"))
           (executable-find "rg"))
  (setq projectile-generic-command
        (let ((rg-cmd ""))
          (dolist (dir projectile-globally-ignored-directories)
            (setq rg-cmd (format "%s --glob '!%s'" rg-cmd dir)))
          (setq rg-ignorefile
                (concat "--ignore-file" " "
                        (expand-file-name "rg_ignore" user-emacs-directory)))
          (concat "rg -0 --files --color=never --hidden" rg-cmd " " rg-ignorefile))))
#+end_src

#+begin_src elisp
(setq completion-styles '(orderless basic)
      completion-category-defaults nil
      completion-category-overrides '((file (styles basic partial-completion))))
#+end_src

** ~emms~ :emms:music:

#+begin_src elisp
;; (setq emms-source-file-directory-tree-function 'emms-source-file-directory-tree-find)
#+end_src

#+begin_src elisp
;; (setq emms-source-file-default-directory "~/Music/")
#+end_src

** Enable active presence on Discord for Emacs
:PROPERTIES:
:ID:       a948faf0-c278-4481-bd1b-c857644a4c90
:END:

*WARNING*: This will tell anyone on your Discord your current activity status in Emacs—with a pretty hefty amount of detail as well. [[id:8f9bc104-87a1-4fa4-b624-a5ea64210b8a][Remember: you can do the following if you want to disable something]].

#+begin_src elisp
(use-package! elcord-mode
  :defer t)

(elcord-mode)
#+end_src

** EPG: Letting Emacs query for GPG passwords

Allow Emacs to handle queries for gpg passwords.

#+begin_src elisp
(setq epg-pinentry-mode 'loopback)

(defun pinentry-emacs (desc prompt ok error)
  (let ((str (read-passwd (concat (replace-regexp-in-string "%22" "\""
                                  (replace-regexp-in-string "%0A" "\n" desc)) prompt ": ")))) str))
#+end_src

** Tramp :tramp:ssh:
*** Tramp FTP doesn't read my ~/.authinfo.gpg :tramp:ssh:

Ange-FTP defaults to =~/.netrc=  so you need to add this to your init script:

#+begin_src elisp
(setq ange-ftp-netrc-filename "~/.authinfo.gpg")
#+end_src

*** Tramp intregration with dirvish :tramp:ssh:dirvish:

#+begin_src elisp
(use-package tramp
  :config
  ;; Enable full-featured Dirvish over TRAMP on certain connections
  ;; https://www.gnu.org/software/tramp/#Improving-performance-of-asynchronous-remote-processes-1.
  (add-to-list 'tramp-connection-properties
               (list (regexp-quote "/ssh:chunix:")
                     "direct-async-process" t))
  ;; Tips to speed up connections
  (setq tramp-verbose 0)
  (setq tramp-chunksize 2000)
  (setq tramp-use-ssh-controlmaster-options nil))
#+end_src

** Palimpsest prog mode hook

#+begin_src elisp
(use-package! palimpsest-mode
  :hook (prog-mode . palimpsest-mode))
#+end_src

** Common Lisp
*** Common Lisp find file fix for Roswell compatibility :lisp:

#+begin_src elisp
(defun +lisp/find-file-in-quicklisp ()
  "Find a file belonging to a library downloaded by Quicklisp."
  (interactive)
  (doom-project-find-file "~/.local/share/roswell/lisp/quicklisp/dists"))
#+end_src

*** ~roswell~ Lisp Sly helper :lisp:roswell:sly:repl:

#+begin_src elisp
(load! (expand-file-name "~/.local/share/roswell/helper.el"))
(setq inferior-lisp-program "ros dynamic-space-size=8000 -Q run")
#+end_src

*** Common Lisp snippets for ya snippets (require)

#+begin_src elisp
(use-package! common-lisp-snippets
  :defer t)
#+end_src

*** Sly completion fix :lisp:

#+begin_src elisp
(after! sly
  (setq sly-complete-symbol-function 'sly-flex-completions))
#+end_src

** mu4e
#+begin_src elisp :results none
(use-package mu4e
  ;; :ensure nil
  ;; :load-path "/usr/share/emacs/site-lisp/mu4e/"
  ;; :defer 20 ; Wait until 20 seconds after startup
  :config
  ;; This is set to 't' to avoid mail syncing issues when using mbsync
  (setq mu4e-change-filenames-when-moving t)
  ;; Refresh mail using isync every 10 minutes
  (setq mu4e-update-interval (* 10 60))
  (setq mu4e-get-mail-command "mbsync -a")
  (setq mu4e-maildir "~/.local/share/mail/")
  (setq mu4e-drafts-folder "/[Gmail]/Drafts")
  (setq mu4e-sent-folder   "/[Gmail]/Sent Mail")
  (setq mu4e-refile-folder "/[Gmail]/All Mail")
  (setq mu4e-trash-folder  "/[Gmail]/Trash")
  (setq mu4e-maildir-shortcuts
        '((:maildir "/Inbox"    :key ?i)
          (:maildir "/[Gmail]/Sent Mail" :key ?s)
          (:maildir "/[Gmail]/Trash"     :key ?t)
          (:maildir "/[Gmail]/Drafts"    :key ?d)
          (:maildir "/[Gmail]/All Mail"  :key ?a)))
  (setq +mu4e-backend 'mbsync
        sendmail-program (executable-find "msmtp")
        send-mail-function #'smtpmail-send-it
        message-sendmail-f-is-evil t
        message-sendmail-extra-arguments '("--read-envelope-from")
        message-send-mail-function #'message-send-mail-with-sendmail
        mu4e-context-policy 'pick-first
        mu4e-contexts
        `(,(make-mu4e-context
            :name "Acalebdeanwatson@gmail.com"
            :enter-func (lambda () (mu4e-message "Entering calebdeanwatson@gmail.com context"))
            :leave-func (lambda () (mu4e-message "Leaving calebdeanwatson@gmail.com context"))
            :match-func (lambda (msg)
                          (when msg
                            (string-match-p "^/gmail.com/calebdeanwatson"
                                            (mu4e-message-field msg :maildir))))
            :vars '((user-mail-address . "calebdeanwatson@gmail.com")
                    (user-full-name . "Caleb D. Watson")
                    (message-signature . (concat "Best regards,\n"
                                                 "Caleb D. Watson\n"))
                    (mu4e-sent-folder . "/gmail.com/calebdeanwatson/[Gmail]/Sent Mail")
                    (mu4e-drafts-folder . "/gmail.com/calebdeanwatson/[Gmail]/Drafts")
                    (mu4e-trash-folder . "/gmail.com/calebdeanwatson/[Gmail]/Trash")))
          ,(make-mu4e-context
            :name "Bchufilthymutt@gmail.com"
            :enter-func (lambda () (mu4e-message "Entering chufilthymutt@gmail.com context"))
            :leave-func (lambda () (mu4e-message "Leaving chufilthymutt@gmail.com context"))
            :match-func (lambda (msg)
                          (when msg
                            (string-match-p "^/gmail.com/chufilthymutt"
                                            (mu4e-message-field msg :maildir))))
            :vars '((user-mail-address . "chufilthymutt@gmail.com")
                    (user-full-name . "Chu")
                    (message-signature . nil)
                    (mu4e-sent-folder . "/gmail.com/chufilthymutt/[Gmail]/Sent Mail")
                    (mu4e-drafts-folder . "/gmail.com/chufilthymutt/[Gmail]/Drafts")
                    (mu4e-trash-folder . "/gmail.com/chufilthymutt/[Gmail]/Trash"))))))
#+end_src

** ~whisper~ Voice transcription (speech to text)

Personally, I can't get a model other than the ~base~ one to download. I'm an English speaker, so there's no translation services enabled.

The ~num-processors~ function is a part of base Emacs: [[https://www.gnu.org/software/emacs/manual/html_node/elisp/Process-Information.html#index-num_002dprocessors][GNU Emacs Manual 40.6 Process Information]].

#+begin_src elisp :results none
(use-package whisper
  :config
  (setq whisper-install-directory "~/.config/emacs/.local/cache/"
        whisper-model "base"
        whisper-language "en"
        whisper-translate nil
        whisper-use-threads (/ (num-processors) 2))
        ;; turn off after 600 seconds of silence
        whisper-recording-timeout 600)
#+end_src

* Works Cited
** [[https://gergely.polonkai.eu/blog/2014/10/7/rounding-numbers-to-n-decimals-in-emacs.html][Rounding numbers to N decimals in Emacs]]
by Gergely Polonkai.
** https://blog.lazkani.io/posts/bookmark-with-org-capture/
** https://orgmode.org/manual/Capture-templates.html
** [[https://raw.githubusercontent.com/gilbertw1/emacs-literate-starter/master/emacs.org][DOOM Emacs Literate Config]]

By Gilbert. Thanks, Gilbert.

** [[https://github.com/alphapapa/unpackaged.el#ensure-blank-lines-between-headings-and-before-contents][alphapapa/unpackaged.el: A collection of useful Emacs Lisp code that isn't substantial enough to be packaged]]

This is where the '~unpackaged/org-fix-blank-lines~' function was sourced from.

By alphapapa. Thanks, alphapapa.

** [[https://stackoverflow.com/a/35475878/259187][org-archive-subtree-hierarchical.el v0.2]]

By [[https://gist.github.com/kepi/2f4acc3cc93403c75fbba5684c5d852d][Kepi]]. Thanks, Kepi.

*** [[https://lists.gnu.org/archive/html/emacs-orgmode/2014-08/msg00109.html][org-archive-subtree-hierarchical.el v0.1]]

By [[https://lists.gnu.org/archive/html/emacs-orgmode/2014-08/msg00109.html][Florian Adamsky]]. Thanks, Florian Adamsky.
